apiVersion: v1
clusters:
- cluster:
    server: https://29CA5D5B9C18660735B2F7799CA49506.gr7.us-east-2.eks.amazonaws.com
  name: my-eks-cluster
contexts:
- context:
    cluster: my-eks-cluster
    user: aws
  name: my-eks-cluster
current-context: my-eks-cluster
kind: Config
preferences: {}
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws
      args:
        - "eks"
        - "get-token"
        - "--region"
        - "us-east-2"
        - "--cluster-name"
        - "my-eks-cluster"
