apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:eks:us-east-2:761018874575:nodegroup/my-eks-cluster/cluster-group/dec8d8b4-ce5f-5a30-3f45-7e0a5c806d60
      username: my-eks-cluster-node
      groups:
        - system:bootstrappers
        - system:nodes
  mapUsers: |
    - userarn: arn:aws:iam::761018874575:user/jenkins-user
      username: jenkins-user
      groups:
        - system:masters
